kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: provision
    image: rohitmisra44/homelab-pipeline-image:1.1.0
    environment:
      BWS_ACCESS_TOKEN:
        from_secret: BWS_ACCESS_TOKEN
    commands:
      - mkdir /run/secrets
      - bws list secrets | jq -r '.[] | "export \(.key)=$(echo \(.value | @base64) | base64 --decode)"' > /run/secrets/export_secrets.sh
      - cat -n /run/secrets/export_secrets.sh
      - chmod +x /run/secrets/export_secrets.sh
      - | 
        . /run/secrets/export_secrets.sh
        env  # Print the environment variables for debugging
        mkdir $HOME/.ssh
        echo "$SSH_PVT_KEY" > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa
        cd k8s/terraform/
        terraform init -input=false
        terraform apply -input=false -auto-approve

trigger:
  event:
    include:
      - push
      - pull_request
