---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:

  - name: provision
    image: rohitmisra44/homelab-pipeline-image
    environment:
      SSH_KEY:
        from_secret: SSH_KEY
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_REGION:
        from_secret: AWS_REGION
      PM_API_TOKEN_ID:
        from_secret: PM_API_TOKEN_ID
      PM_API_TOKEN_SECRET:
        from_secret: PM_API_TOKEN_SECRET
      TF_VAR_master_ip:
        from_secret: TF_VAR_master_ip
      TF_VAR_pm_api_url:
        from_secret: TF_VAR_pm_api_url
      TF_VAR_rancher_ca_checksum:
        from_secret: TF_VAR_rancher_ca_checksum
      TF_VAR_rancher_ip:
        from_secret: TF_VAR_rancher_ip
      TF_VAR_rancher_token:
        from_secret: TF_VAR_rancher_token
      TF_VAR_worker_ips:
        from_secret: TF_VAR_worker_ips
    commands:
      - mkdir $HOME/.ssh
      - echo "$SSH_KEY" > $HOME/.ssh/id_rsa
      - chmod 600 $HOME/.ssh/id_rsa
      - cd k8s/terraform/
      - terraform init -input=false
      - terraform apply -input=false -auto-approve

trigger:
  event:
    include:
      - push
      - pull_request