kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: provision
    image: rohitmisra44/homelab-pipeline-image:1.1.0
    environment:
      BWS_ACCESS_TOKEN:
        from_secret: BWS_ACCESS_TOKEN
    commands:
      - mkdir -p /run/secrets
      - |
        bws list secrets | jq -r '.[] | "echo export \(.key)=$'\''\(.value)'\''" >> /run/secrets/exec_script.sh'
      - cat /run/secrets/secrets.env  # Debug: Print the contents of the file
      - echo '#!/bin/sh' > /run/secrets/exec_script.sh
      - echo '. /run/secrets/secrets.env' >> /run/secrets/exec_script.sh
      - echo 'echo "Environment variables set successfully!"' >> /run/secrets/exec_script.sh
      - chmod +x /run/secrets/exec_script.sh
      - /run/secrets/exec_script.sh
      - mkdir $HOME/.ssh
      - echo "$SSH_PVT_KEY" > $HOME/.ssh/id_rsa
      - chmod 600 $HOME/.ssh/id_rsa
      - cd k8s/terraform/
      - terraform init -input=false
      - terraform apply -input=false -auto-approve

trigger:
  event:
    include:
      - push
      - pull_request
