---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Debug - Starting Cloud-Init Wait
    debug:
      msg: "Starting Cloud-Init Wait"

  - name: Wait for cloud-init / user-data to finish
    command: cloud-init status --wait
    changed_when: false

  - name: Debug - Finished Cloud-Init Wait
    debug:
      msg: "Finished Cloud-Init Wait"

  - name: Debug - Starting Package Installation
    debug:
      msg: "Starting Package Installation"

  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - nfs-common  # NFS client package

  - name: Debug - Finished Package Installation
    debug:
      msg: "Finished Package Installation"

  - name: Debug - Adding Docker Apt Signing Key
    debug:
      msg: "Adding Docker Apt Signing Key"

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Debug - Finished Adding Docker Apt Signing Key
    debug:
      msg: "Finished Adding Docker Apt Signing Key"

  - name: Debug - Adding Docker Apt Repository
    debug:
      msg: "Adding Docker Apt Repository"

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Debug - Finished Adding Docker Apt Repository
    debug:
      msg: "Finished Adding Docker Apt Repository"

  - name: Debug - Starting Docker Installation
    debug:
      msg: "Starting Docker Installation"

  - name: Install docker and its dependencies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io
    notify:
      - Start Docker

  - name: Debug - Finished Docker Installation
    debug:
      msg: "Finished Docker Installation"

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      group: docker
      append: yes

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Ensure Docker is running
    service:
      name: docker
      state: started
      enabled: yes

  - name: Debug - Checking Rancher Agent
    debug:
      msg: "Checking if Rancher agent is already running"

  - name: Check if Rancher agent is already running
    shell: sudo docker ps | grep rancher/hyperkube
    register: rancher_agent_running
    changed_when: false
    ignore_errors: yes

  - name: Debug - Rancher Agent Check Done
    debug:
      msg: "Rancher agent running status: {{ rancher_agent_running }}"

  - name: Register with Rancher server
    command: sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.7.5 --server {{ rancherip }} --token {{ ranchertoken }} --ca-checksum {{ ranchercachecksum }} --node-name {{ nodename }} --address {{ nodeip }} --worker
    when: rancher_agent_running.stdout == ""

  - name: Debug - Creating Mount Directory
    debug:
      msg: "Creating Mount Directory"

  - name: Create mount directory
    file:
      path: /mnt/nfs
      state: directory

  - name: Debug - Mounting NFS Share
    debug:
      msg: "Mounting NFS Share"

  - name: Mount NFS share
    mount:
      src: nas-dsm-01:/volume1/homelab-k8s
      path: /mnt/nfs
      fstype: nfs
      opts: rw,noauto,user
      state: mounted

  - name: Ensure correct permissions on NFS mount directory
    file:
      path: /mnt/nfs
      state: directory
      owner: ubuntu
      group: ubuntu
      mode: '0775'

  handlers:
  - name: Start Docker
    service:
      name: docker
      state: started
      enabled: yes
